name:                aoc2025
version:             0.1.0.0
github:              "spx01/aoc2025"
license:             MIT
author:              "spx01"
maintainer:          "spx01@protonmail.com"
copyright:           "2025 spx01"

extra-source-files:  []

description:         AoC 2025

dependencies:
- base >= 4.7 && < 5
- bifunctors
- filepath
- split
- containers
- mtl
- clock
- linear
- vector
- sbv
- lens
- fgl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing

language: GHC2021
default-extensions:
- LambdaCase
- OverloadedStrings
- OverloadedLabels
- DataKinds
- StandaloneKindSignatures
- TypeFamilies
- DerivingStrategies
- ViewPatterns

library:
  source-dirs: src

executables:
  day00:
    main:                Main.hs
    source-dirs:         app/Day00
    dependencies:
    - aoc2025
  day01:
    main:                Main.hs
    source-dirs:         app/Day01
    dependencies:
    - aoc2025
  day02:
    main:                Main.hs
    source-dirs:         app/Day02
    dependencies:
    - aoc2025
  day03:
    main:                Main.hs
    source-dirs:         app/Day03
    dependencies:
    - aoc2025
  day04:
    main:                Main.hs
    source-dirs:         app/Day04
    dependencies:
    - aoc2025
  day05:
    main:                Main.hs
    source-dirs:         app/Day05
    dependencies:
    - aoc2025
  day06:
    main:                Main.hs
    source-dirs:         app/Day06
    dependencies:
    - aoc2025
  day07:
    main:                Main.hs
    source-dirs:         app/Day07
    dependencies:
    - aoc2025
  day07b:
    main:                Main.hs
    source-dirs:         app/Day07b
    dependencies:
    - aoc2025
  day08:
    main:                Main.hs
    source-dirs:         app/Day08
    dependencies:
    - aoc2025
  day08b:
    main:                Main.hs
    source-dirs:         app/Day08b
    dependencies:
    - aoc2025
  day09:
    main:                Main.hs
    source-dirs:         app/Day09
    dependencies:
    - aoc2025
  day09b:
    main:                Main.hs
    source-dirs:         app/Day09b
    dependencies:
    - aoc2025
  day10:
    main:                Main.hs
    source-dirs:         app/Day10
    dependencies:
    - aoc2025
  day11:
    main:                Main.hs
    source-dirs:         app/Day11
    dependencies:
    - aoc2025

tests:
  aoc2025-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - aoc2025
